package com.remindcare.ui

import android.Manifest
import android.content.Context
import android.content.pm.PackageManager
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.FileProvider
import com.remindcare.CareViewModel
import com.remindcare.data.*
import java.io.File
import java.time.format.DateTimeFormatter
import java.time.LocalTime

@Composable fun RoleScreen(vm:CareViewModel){var name by remember{mutableStateOf("")}; Column(Modifier.fillMaxSize().padding(28.dp),verticalArrangement=Arrangement.spacedBy(22.dp),horizontalAlignment=Alignment.CenterHorizontally){Spacer(Modifier.height(36.dp));Text("RemindCare",fontSize=38.sp,fontWeight=FontWeight.Bold);Text("Gentle help for every day",fontSize=20.sp);OutlinedTextField(name,{name=it},label={Text("Your name")},singleLine=true,modifier=Modifier.fillMaxWidth());Text("Choose how you will use RemindCare",fontSize=20.sp);RoleButton("I am a Patient",Icons.Default.Favorite){vm.choose(UserRole.PATIENT,name.ifBlank{"Patient"})};RoleButton("I am a Caregiver",Icons.Default.People){vm.choose(UserRole.CAREGIVER,name.ifBlank{"Caregiver"})};Text("All information stays safely on this device.",fontSize=15.sp)}}
@Composable private fun RoleButton(label:String,icon:androidx.compose.ui.graphics.vector.ImageVector,on:()->Unit){Button(on,Modifier.fillMaxWidth().height(96.dp),shape=RoundedCornerShape(28.dp)){Icon(icon,null,Modifier.size(36.dp));Spacer(Modifier.width(18.dp));Text(label,fontSize=24.sp)}}

@Composable fun HomeScreen(vm:CareViewModel,profile:ProfileEntity){var page by remember{mutableStateOf("home")}; var edit by remember{mutableStateOf<ReminderEntity?>(null)}; when { page=="create" -> EditReminderScreen(edit,{vm.save(it);page="home"},{page="home"}); page=="history" -> HistoryScreen(vm.history,{page="home"}); page=="pair" -> PairingScreen(profile,{page="home"}); else -> { if(profile.role==UserRole.PATIENT) PatientScreen(vm,profile,{page="history"},{page="pair"}) else CaregiverScreen(vm,profile,{edit=null;page="create"},{edit=it;page="create"},{vm.remove(it)},{page="history"},{page="pair"}) } }}
@Composable fun PatientScreen(vm:CareViewModel,p:ProfileEntity,history:()->Unit,pair:()->Unit){ val done=vm.history.filter{it.status==CompletionStatus.COMPLETED}.map{it.reminderId}.toSet(); Scaffold(topBar={TopAppBar(title={Text("Hello, ${p.displayName}",fontSize=26.sp)},actions={IconButton(pair){Icon(Icons.Default.QrCode,null)}})},bottomBar={NavigationBar{NavigationBarItem(true,{}, {Icon(Icons.Default.Home,null)},{Text("Today")});NavigationBarItem(false,history,{Icon(Icons.Default.History,null)},{Text("History")})}}){pad->Column(Modifier.padding(pad).padding(20.dp)){Text("Today's Tasks",fontSize=30.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(16.dp));LazyColumn(verticalArrangement=Arrangement.spacedBy(14.dp)){items(vm.reminders){r->PatientTask(r,r.id in done){photo->vm.complete(r.id,photo)}}}}}}
@Composable private fun PatientTask(r:ReminderEntity,completed:Boolean,onDone:(String?)->Unit){ val context=LocalContext.current; var photoUri by remember{mutableStateOf<Uri?>(null)}; val camera=rememberLauncherForActivityResult(ActivityResultContracts.TakePicture()){ok->if(ok)onDone(photoUri?.toString())}; val requestCamera=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){granted->if(granted)photoUri?.let{camera.launch(it)}}; fun finishTask(){if(r.requiresPhoto){val file=File(context.filesDir,"proofs/${System.currentTimeMillis()}.jpg").also{it.parentFile?.mkdirs()};photoUri=FileProvider.getUriForFile(context,"${context.packageName}.files",file);if(ContextCompat.checkSelfPermission(context,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)camera.launch(photoUri!!) else requestCamera.launch(Manifest.permission.CAMERA)}else onDone(null)};Card(Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(containerColor=if(completed)Color(0xFFD9F3E4) else MaterialTheme.colorScheme.surfaceVariant),shape=RoundedCornerShape(24.dp)){Row(Modifier.padding(20.dp),verticalAlignment=Alignment.CenterVertically){Icon(if(completed)Icons.Default.CheckCircle else Icons.Default.Alarm,null,Modifier.size(38.dp),tint=if(completed)Color(0xFF167A45) else MaterialTheme.colorScheme.primary);Spacer(Modifier.width(16.dp));Column(Modifier.weight(1f)){Text(r.title,fontSize=23.sp,fontWeight=FontWeight.SemiBold);Text(LocalTime.of(r.hour,r.minute).format(DateTimeFormatter.ofPattern("h:mm a")),fontSize=18.sp);if(r.requiresPhoto)Text("Photo required",fontSize=14.sp)};if(!completed)Button({finishTask()},Modifier.height(54.dp)){Text("Done",fontSize=18.sp)}}}}

@Composable fun CaregiverScreen(vm:CareViewModel,p:ProfileEntity,add:()->Unit,edit:(ReminderEntity)->Unit,remove:(ReminderEntity)->Unit,history:()->Unit,pair:()->Unit){Scaffold(topBar={TopAppBar(title={Column{Text("Caregiver Dashboard",fontSize=24.sp);Text(p.displayName,fontSize=14.sp)}},actions={IconButton(pair){Icon(Icons.Default.QrCode,null)}})},floatingActionButton={ExtendedFloatingActionButton(add,icon={Icon(Icons.Default.Add,null)},text={Text("Add reminder",fontSize=18.sp)})},bottomBar={NavigationBar{NavigationBarItem(true,{}, {Icon(Icons.Default.Today,null)},{Text("Today")});NavigationBarItem(false,history,{Icon(Icons.Default.History,null)},{Text("History")})}}){pad->LazyColumn(Modifier.padding(pad).padding(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Today's reminders",fontSize=27.sp,fontWeight=FontWeight.Bold)};items(vm.reminders){r->Card(Modifier.fillMaxWidth().clickable{edit(r)},shape=RoundedCornerShape(20.dp)){Row(Modifier.padding(18.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Alarm,null,Modifier.size(32.dp));Spacer(Modifier.width(16.dp));Column(Modifier.weight(1f)){Text(r.title,fontSize=21.sp);Text("${LocalTime.of(r.hour,r.minute).format(DateTimeFormatter.ofPattern("h:mm a"))} • ${r.type.name.lowercase()}")};IconButton({remove(r)}){Icon(Icons.Default.Delete,null)}}}}}}}

@Composable fun EditReminderScreen(existing:ReminderEntity?,save:(ReminderEntity)->Unit,cancel:()->Unit){var title by remember{mutableStateOf(existing?.title?:"")};var type by remember{mutableStateOf(existing?.type?:ReminderType.MEDICINE)};var hour by remember{mutableStateOf(existing?.hour?:9)};var minute by remember{mutableStateOf(existing?.minute?:0)};var quantity by remember{mutableStateOf(existing?.quantity?:"")};var location by remember{mutableStateOf(existing?.location?:"")};var notes by remember{mutableStateOf(existing?.notes?:"")};var proof by remember{mutableStateOf(existing?.requiresPhoto?:false)};var image by remember{mutableStateOf(existing?.imageUri)};var menu by remember{mutableStateOf(false)}; val picker=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){image=it?.toString()}
 Scaffold(topBar={TopAppBar(title={Text(if(existing==null)"New Reminder" else "Edit Reminder")},navigationIcon={IconButton(cancel){Icon(Icons.Default.ArrowBack,null)}})}){pad->LazyColumn(Modifier.padding(pad).padding(22.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Text("Keep it simple and clear.",fontSize=18.sp)};item{OutlinedTextField(title,{title=it},label={Text("Reminder title")},modifier=Modifier.fillMaxWidth(),textStyle=LocalTextStyle.current.copy(fontSize=21.sp))};item{OutlinedButton({picker.launch("image/*")},Modifier.fillMaxWidth().height(56.dp)){Icon(Icons.Default.Image,null);Spacer(Modifier.width(10.dp));Text(if(image==null)"Add a reminder image" else "Image selected")}};item{Box{OutlinedButton({menu=true},Modifier.fillMaxWidth().height(58.dp)){Text("Type: ${type.name.lowercase().replaceFirstChar{it.uppercase()}",fontSize=18.sp)};DropdownMenu(menu,{menu=false}){ReminderType.entries.forEach{t->DropdownMenuItem({Text(t.name.lowercase().replaceFirstChar{it.uppercase()})},{type=t;menu=false})}}}};item{Row(horizontalArrangement=Arrangement.spacedBy(12.dp)){OutlinedTextField(hour.toString(),{hour=it.filter(Char::isDigit).toIntOrNull()?.coerceIn(0,23)?:hour},label={Text("Hour (0–23)")},modifier=Modifier.weight(1f));OutlinedTextField(minute.toString(),{minute=it.filter(Char::isDigit).toIntOrNull()?.coerceIn(0,59)?:minute},label={Text("Minute")},modifier=Modifier.weight(1f))}};item{OutlinedTextField(quantity,{quantity=it},label={Text("Quantity (optional)")},modifier=Modifier.fillMaxWidth())};item{OutlinedTextField(location,{location=it},label={Text("Location (optional)")},modifier=Modifier.fillMaxWidth())};item{OutlinedTextField(notes,{notes=it},label={Text("Additional notes")},modifier=Modifier.fillMaxWidth(),minLines=2)};item{Row(verticalAlignment=Alignment.CenterVertically){Checkbox(proof,{proof=it});Text("Require photo confirmation",fontSize=18.sp)}};item{Button({if(title.isNotBlank())save(ReminderEntity(id=existing?.id?:0,title=title,type=type,hour=hour,minute=minute,imageUri=image,quantity=quantity,location=location,notes=notes,requiresPhoto=proof))},Modifier.fillMaxWidth().height(68.dp)){Text("SAVE REMINDER",fontSize=20.sp)}}}}}

@Composable fun HistoryScreen(items:List<HistoryEntity>,back:()->Unit){Scaffold(topBar={TopAppBar(title={Text("Completion History",fontSize=24.sp)},navigationIcon={IconButton(back){Icon(Icons.Default.ArrowBack,null)}})}){pad->LazyColumn(Modifier.padding(pad).padding(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){if(items.isEmpty())item{Text("No reminders have been recorded yet.",fontSize=20.sp)};items(items){h->Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp)){Row(Modifier.padding(18.dp),verticalAlignment=Alignment.CenterVertically){Icon(when(h.status){CompletionStatus.COMPLETED->Icons.Default.CheckCircle;CompletionStatus.MISSED->Icons.Default.Warning;else->Icons.Default.Schedule},null,Modifier.size(32.dp));Spacer(Modifier.width(14.dp));Column{Text(h.title,fontSize=21.sp);Text(h.status.name.lowercase().replaceFirstChar{it.uppercase()},fontSize=17.sp)}}}}}}}

@Composable fun PairingScreen(profile:ProfileEntity,back:()->Unit){Scaffold(topBar={TopAppBar(title={Text("Pair Devices")},navigationIcon={IconButton(back){Icon(Icons.Default.ArrowBack,null)}})}){pad->Column(Modifier.padding(pad).padding(28.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(24.dp)){Text("Connect a Caregiver and Patient",fontSize=28.sp);Text("Use this code on the other device.",fontSize=20.sp);Text(profile.pairingCode.ifBlank{"123456"},fontSize=44.sp,fontWeight=FontWeight.Bold,modifier=Modifier.background(MaterialTheme.colorScheme.surfaceVariant,RoundedCornerShape(20.dp)).padding(24.dp));Text("Local pairing is ready for a future direct device connection. This offline version keeps each device's information private.",fontSize=17.sp);Button(back,Modifier.fillMaxWidth().height(64.dp)){Text("DONE",fontSize=20.sp)}}}
